#!/usr/bin/env python3
# Pre-compress immutable JS/CSS assets at build time. Mirrors the parent
# ESPGeiger scripts/gzip_assets.py, trimmed to a single page.
#
# Each ASSET is a (source_file, symbol, content_type) triple. The
# R"DELIM(...)DELIM" body of the named PROGMEM symbol is extracted,
# gzipped, and emitted to <BUILD_DIR>/generated/<SYM>.gz.h as:
#   #define EG_GZ_<SYM> 1
#   static const size_t  <SYM>_GZ_LEN = ...;
#   static const uint8_t <SYM>_GZ[] PROGMEM = { ... };
#
# Per-asset failure falls back to EG_GZ_<SYM> 0; consumers then take the
# raw R"..." path. Build never fails because of this script.

import gzip
import io
import os
import re
import sys

ASSETS = [
    ("src/WebServer/WebServer.cpp", "INDEX_JS",  "application/javascript"),
    ("src/WebServer/WebServer.cpp", "STYLE_CSS", "text/css"),
]

RAW_RE_TMPL = (
    r'(?:extern|static)\s+const\s+char\s+{name}\s*\[\s*\]\s*PROGMEM\s*=\s*'
    r'R"([A-Za-z0-9_]+)\((.*?)\)\1"\s*;'
)


def extract_raw(src_path, sym):
    with open(src_path, "r", encoding="utf-8") as f:
        text = f.read()
    m = re.search(RAW_RE_TMPL.format(name=re.escape(sym)), text, re.DOTALL)
    return m.group(2).encode("utf-8") if m else None


def gzip_bytes(payload):
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as gz:
        gz.write(payload)
    return buf.getvalue()


def emit_header(out_path, name, ok, blob=None, raw_len=0):
    lines = [
        "// Generated by scripts/gzip_assets.py - do not edit.",
        f"// Source symbol: {name}",
    ]
    if ok:
        ratio = (100 * len(blob) // raw_len) if raw_len else 0
        lines.append(f"// Raw {raw_len} B -> gzip {len(blob)} B ({ratio}%)")
        lines.append("")
        lines.append(f"#define EG_GZ_{name} 1")
        lines.append(f"static const size_t {name}_GZ_LEN = {len(blob)};")
        lines.append(f"static const uint8_t {name}_GZ[] PROGMEM = {{")
        for i in range(0, len(blob), 16):
            chunk = blob[i:i + 16]
            lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        lines.append("};")
    else:
        lines.append(f"#define EG_GZ_{name} 0")
    lines.append("")
    new_text = "\n".join(lines)

    if os.path.exists(out_path):
        with open(out_path, "r", encoding="utf-8") as f:
            if f.read() == new_text:
                return
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(new_text)


def process(project_dir, gen_dir, rel_path, sym):
    out_path = os.path.join(gen_dir, f"{sym}.gz.h")
    try:
        raw = extract_raw(os.path.join(project_dir, rel_path), sym)
        if raw is None:
            print(f"[gzip_assets] {sym}: extract miss in {rel_path}; raw fallback")
            emit_header(out_path, sym, ok=False)
            return
        blob = gzip_bytes(raw)
        emit_header(out_path, sym, ok=True, blob=blob, raw_len=len(raw))
        print(f"[gzip_assets] {sym}: {len(raw)} -> {len(blob)} B "
              f"({100 * len(blob) // len(raw)}%)")
    except Exception as e:
        print(f"[gzip_assets] {sym}: {e}; raw fallback")
        emit_header(out_path, sym, ok=False)


def run(project_dir, gen_dir):
    os.makedirs(gen_dir, exist_ok=True)
    for rel_path, sym, _ in ASSETS:
        process(project_dir, gen_dir, rel_path, sym)


# PIO entry point.
try:
    Import("env")  # type: ignore  # noqa: F821
    _project_dir = env["PROJECT_DIR"]  # type: ignore  # noqa: F821
    _build_dir = env.subst("$BUILD_DIR")  # type: ignore  # noqa: F821
    _gen_dir = os.path.join(_build_dir, "generated")
    run(_project_dir, _gen_dir)
    env.Append(CPPPATH=[_gen_dir])  # type: ignore  # noqa: F821
except NameError:
    if __name__ == "__main__":
        gen = sys.argv[1] if len(sys.argv) > 1 else "build_test/generated"
        run(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), gen)
